services:
  db:
    image: postgres:latest
    container_name: api_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gym
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local
